name: Build Firmware

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'version.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make hash_str2file
      env:
        SECRETS_SECURE_BOOT_PASS: ${{ secrets.SECURE_BOOT_PASS }}
      run: |
        ./build.sh
        echo ${SECRETS_SECURE_BOOT_PASS} >pass.txt


    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: hash_str2file_b
        path: |
          hs
          pass.txt
          build.log
