name: My Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make hash_str2file
      run: make

    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R
