name: My Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make hash_str2file
      run: make

    - uses: actions/checkout@v2

    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: hash_str2file_b
        path: |
          hs
          src

    - uses: actions/download-artifact@v2.0.10
      with:
        name: hash_str2file_b

    - name: Display structure of downloaded files
      run: ls -R
