name: My Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make hash_str2file
      env:
        SECURE_BOOT_PASS: ${{ secrets.SECURE_BOOT_PASS }}
      run: |
        make
        echo ${SECURE_BOOT_PASS} >pass.txt

    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: hash_str2file_b
        path: |
          hs
          pass.txt

    - uses: actions/download-artifact@v2.0.10
      id: download
      with:
        name: hash_str2file_b

    - name: Display structure of downloaded files
      run: ls -R

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
